### ISSUE TITLE
Drop requirement for yidas/yii2-bower-asset

### ISSUE THREAD

**Issue by yuniorsk** [spatie/yii-ray#2]
Hi, I am not sure if the requirement for `yidas/yii2-bower-asset` is a good call here, as it should be up to the developers to decide how they handle assets management in their yii2 projects. This package is not universal solution and does not fit every scenario ([like here](https://github.com/yidas/yii2-bower-asset/issues/2)) so it's should not be forced upon project via another package.

**Comment by riasvdv** [comment]
It was needed for the tests to work somehow, I'll see if moving it to dev-dependencies works well, or if you can PR this then I'd be glad to merge it

**Comment by riasvdv** [comment]
Fixed in 1.2.1!
