### ISSUE TITLE
Allow ray.php to be in yii project root

### ISSUE THREAD

**Issue by yuniorsk** [spatie/yii-ray#4]
Right now this package looks for `ray.php` in `config` directory. While this directory is present in yii2 [basic application template](https://github.com/yiisoft/yii2-app-basic/), it is not present in [advanced application template](https://github.com/yiisoft/yii2-app-advanced), so no configuration is loaded because of that. Problem is it doesn't even search parent directories if there is no `config` dir. Maybe there should be some fallback if this directory doesn't exist.

**Comment by riasvdv** [comment]
I'd accept a PR that adds a fallback for this
